
import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    home: 'Home',
    cars: 'Cars',
    compare: 'Compare',
    customerEnquiry: 'Customer Enquiry',
    about: 'About',
    contact: 'Contact',
    login: 'Login',
    signUp: 'Sign Up',
    continueWithGoogle: 'Continue with Google',
    forgotPassword: 'Forgot Password?',
    wishlist: 'Wishlist',
    logout: 'Logout',
    moreInformation: 'More Information',
    yourProfile: 'Your Profile',
    adminPanel: 'Admin Panel',
    adminLogin: 'Admin Login',
    notifications: 'Notifications',
    selectLanguage: 'Select Language',
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    passwordStrength: 'Password Strength',
    weak: 'Weak',
    medium: 'Medium',
    strong: 'Strong',
    signupSuccess: 'Account created successfully! Please login.',
    invalidCredentials: 'Invalid email or password.',
    emailRegistered: 'Email already registered.',
    passwordMismatch: 'Passwords do not match.',
    enterEmail: 'Enter your email',
    password: 'Password',
    enterPassword: 'Enter your password',
    resetPassword: 'Reset Password',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    passwordResetSent: 'Password reset link sent to your email.',
    loginAsAdmin: 'Login as Admin',
    loginAsUser: 'Login as User',
    // Home Page
    heroTitle: 'Trusted Second-Hand Car Marketplace',
    heroSubtitle: 'Find your perfect pre-owned vehicle with transparent pricing and quality assurance',
    viewCars: 'View Cars',
    bookVisit: 'Book Visit',
    aboutTitle: 'Why Choose Us?',
    aboutDescription: 'We are a trusted showroom with years of experience in the second-hand car market. Every vehicle is quality-checked, and we offer transparent pricing with trusted sellers.',
    yearsExperience: 'Years of Experience',
    qualityChecked: 'Quality-Checked Vehicles',
    transparentPricing: 'Transparent Pricing',
    trustedSellers: 'Trusted Sellers',
    verifiedCars: 'Verified Cars',
    trustedDealers: 'Trusted Dealers',
    customerSatisfaction: 'Customer Satisfaction',
    recentlySold: 'Recently Sold',
    recentlyAdded: 'Recently Added',
    new: 'New',
    sold: 'Sold',
    viewDetails: 'View Details',
    quickContact: 'Quick Contact',
    quickContactSubtitle: 'Get in touch with us for any enquiries',
    name: 'Name',
    phone: 'Phone Number',
    email: 'Email',
    message: 'Message',
    submit: 'Submit',
    submitEnquiry: 'Submit Enquiry',
    enquirySuccess: 'Thank you! We will contact you soon.',
    thanksForSubmission: 'Thanks for your submission',
    ctaTitle: 'Ready to Find Your Perfect Car?',
    ctaSubtitle: 'Book a visit to our showroom or talk to our experts today',
    talkToExpert: 'Talk to an Expert',
    exploreCars: 'Explore Cars',
    showroomAddress: 'Showroom Address',
    workingHours: 'Working Hours',
    mondayFriday: 'Monday - Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    closed: 'Closed',
    followUs: 'Follow Us',
    allRightsReserved: 'All rights reserved',
    // Profile
    firstName: 'First Name',
    lastName: 'Last Name',
    location: 'Location',
    locationPlaceholder: 'City, State or Region',
    save: 'Save',
    saving: 'Saving...',
    profileUpdated: 'Profile updated successfully.',
    profileUpdateFailed: 'Failed to update profile.',
    editProfileSubtitle: 'View and edit your account information',
    emailNotEditable: 'Email cannot be changed',
    loading: 'Loading...',
  },
  ta: {
    home: 'வீடு',
    cars: 'கார்கள்',
    compare: 'ஒப்பிடு',
    customerEnquiry: 'வாடிக்கையாளர் விசாரணை',
    about: 'பற்றி',
    contact: 'தொடர்பு',
    login: 'உள்நுழை',
    signUp: 'பதிவு செய்',
    continueWithGoogle: 'Google உடன் தொடரவும்',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    wishlist: 'விருப்பப்பட்டியல்',
    logout: 'வெளியேறு',
    moreInformation: 'மேலும் தகவல்',
    yourProfile: 'உங்கள் சுயவிவரம்',
    adminPanel: 'நிர்வாக பேனல்',
    notifications: 'அறிவிப்புகள்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடு',
    // Home Page
    heroTitle: 'நம்பகமான இரண்டாம் கை கார் சந்தை',
    heroSubtitle: 'வெளிப்படையான விலை மற்றும் தர உத்தரவாதத்துடன் உங்கள் சரியான பயன்படுத்தப்பட்ட வாகனத்தைக் கண்டறியவும்',
    viewCars: 'கார்களைக் காண்க',
    bookVisit: 'வருகையை முன்பதிவு செய்க',
    aboutTitle: 'ஏன் எங்களைத் தேர்ந்தெடுக்க வேண்டும்?',
    aboutDescription: 'நாங்கள் இரண்டாம் கை கார் சந்தையில் பல ஆண்டுகளின் அனுபவம் கொண்ட நம்பகமான ஷோரூம். ஒவ்வொரு வாகனமும் தர சரிபார்ப்பு செய்யப்பட்டது, மற்றும் நம்பகமான விற்பனையாளர்களுடன் வெளிப்படையான விலை நிர்ணயத்தை வழங்குகிறோம்.',
    yearsExperience: 'ஆண்டுகள் அனுபவம்',
    qualityChecked: 'தர சரிபார்ப்பு செய்யப்பட்ட வாகனங்கள்',
    transparentPricing: 'வெளிப்படையான விலை',
    trustedSellers: 'நம்பகமான விற்பனையாளர்கள்',
    verifiedCars: 'சரிபார்க்கப்பட்ட கார்கள்',
    trustedDealers: 'நம்பகமான விற்பனையாளர்கள்',
    customerSatisfaction: 'வாடிக்கையாளர் திருப்தி',
    recentlySold: 'சமீபத்தில் விற்கப்பட்டது',
    recentlyAdded: 'சமீபத்தில் சேர்க்கப்பட்டது',
    new: 'புதியது',
    sold: 'விற்கப்பட்டது',
    viewDetails: 'விவரங்களைக் காண்க',
    quickContact: 'விரைவான தொடர்பு',
    quickContactSubtitle: 'எந்தவொரு விசாரணைக்கும் எங்களைத் தொடர்பு கொள்ளவும்',
    name: 'பெயர்',
    phone: 'தொலைபேசி எண்',
    email: 'மின்னஞ்சல்',
    message: 'செய்தி',
    submit: 'சமர்ப்பிக்க',
    submitEnquiry: 'விசாரணையை சமர்ப்பிக்க',
    enquirySuccess: 'நன்றி! நாங்கள் விரைவில் உங்களைத் தொடர்பு கொள்வோம்.',
    thanksForSubmission: 'உங்கள் சமர்ப்பிப்பிற்கு நன்றி',
    ctaTitle: 'உங்கள் சரியான காரைக் கண்டுபிடிக்க தயாரா?',
    ctaSubtitle: 'எங்கள் ஷோரூமிற்கு வருகையை முன்பதிவு செய்யவும் அல்லது இன்றே எங்கள் நிபுணர்களுடன் பேசவும்',
    talkToExpert: 'நிபுணருடன் பேச',
    exploreCars: 'கார்களை ஆராய',
    showroomAddress: 'ஷோரூம் முகவரி',
    workingHours: 'வேலை நேரங்கள்',
    mondayFriday: 'திங்கள் - வெள்ளி',
    saturday: 'சனி',
    sunday: 'ஞாயிறு',
    closed: 'மூடப்பட்டது',
    followUs: 'எங்களைப் பின்தொடர',
    allRightsReserved: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டுள்ளன',
    firstName: 'முதல் பெயர்',
    lastName: 'கடைசி பெயர்',
    location: 'இருப்பிடம்',
    locationPlaceholder: 'நகரம், மாநிலம் அல்லது பிராந்தியம்',
    save: 'சேமிக்கவும்',
    saving: 'சேமிக்கப்படுகிறது...',
    profileUpdated: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது.',
    profileUpdateFailed: 'சுயவிவரத்தை புதுப்பிக்க முடியவில்லை.',
    editProfileSubtitle: 'உங்கள் கணக்கு தகவல்களைக் காண்பித்து திருத்துங்கள்',
    emailNotEditable: 'மின்னஞ்சலை மாற்ற முடியாது',
    loading: 'ஏற்றுகிறது...',
  },
  kn: {
    home: 'ಮುಖಪುಟ',
    cars: 'ಕಾರುಗಳು',
    compare: 'ಹೋಲಿಸಿ',
    customerEnquiry: 'ಗ್ರಾಹಕ ವಿಚಾರಣೆ',
    about: 'ಬಗ್ಗೆ',
    contact: 'ಸಂಪರ್ಕ',
    login: 'ಲಾಗಿನ್',
    signUp: 'ಸೈನ್ ಅಪ್',
    continueWithGoogle: 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    forgotPassword: 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿದೆಯೇ?',
    wishlist: 'ಇಷ್ಟಪಟ್ಟ ಪಟ್ಟಿ',
    logout: 'ಲಾಗ್ ಔಟ್',
    moreInformation: 'ಹೆಚ್ಚಿನ ಮಾಹಿತಿ',
    yourProfile: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
    adminPanel: 'ನಿರ್ವಾಹಕ ಫಲಕ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    // Home Page
    heroTitle: 'ನಂಬಲರ್ಹ ಎರಡನೇ ಕೈ ಕಾರು ಮಾರುಕಟ್ಟೆ',
    heroSubtitle: 'ಪಾರದರ್ಶಕ ಬೆಲೆ ಮತ್ತು ಗುಣಮಟ್ಟದ ಖಾತರಿಯೊಂದಿಗೆ ನಿಮ್ಮ ಪರಿಪೂರ್ಣ ಬಳಸಿದ ವಾಹನವನ್ನು ಹುಡುಕಿ',
    viewCars: 'ಕಾರುಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    bookVisit: 'ಭೇಟಿಯನ್ನು ಬುಕ್ ಮಾಡಿ',
    aboutTitle: 'ಏಕೆ ನಮ್ಮನ್ನು ಆರಿಸಬೇಕು?',
    aboutDescription: 'ನಾವು ಎರಡನೇ ಕೈ ಕಾರು ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ವರ್ಷಗಳ ಅನುಭವವನ್ನು ಹೊಂದಿರುವ ನಂಬಲರ್ಹ ಶೋರೂಮ್. ಪ್ರತಿ ವಾಹನವನ್ನು ಗುಣಮಟ್ಟದ ಪರಿಶೀಲನೆ ಮಾಡಲಾಗುತ್ತದೆ, ಮತ್ತು ನಾವು ನಂಬಲರ್ಹ ಮಾರಾಟಗಾರರೊಂದಿಗೆ ಪಾರದರ್ಶಕ ಬೆಲೆ ನಿಗದಿಯನ್ನು ಒದಗಿಸುತ್ತೇವೆ.',
    yearsExperience: 'ವರ್ಷಗಳ ಅನುಭವ',
    qualityChecked: 'ಗುಣಮಟ್ಟದ ಪರಿಶೀಲನೆ ಮಾಡಿದ ವಾಹನಗಳು',
    transparentPricing: 'ಪಾರದರ್ಶಕ ಬೆಲೆ',
    trustedSellers: 'ನಂಬಲರ್ಹ ಮಾರಾಟಗಾರರು',
    verifiedCars: 'ಪರಿಶೀಲಿಸಿದ ಕಾರುಗಳು',
    trustedDealers: 'ನಂಬಲರ್ಹ ವ್ಯಾಪಾರಿಗಳು',
    customerSatisfaction: 'ಗ್ರಾಹಕ ತೃಪ್ತಿ',
    recentlySold: 'ಇತ್ತೀಚೆಗೆ ಮಾರಾಟ',
    recentlyAdded: 'ಇತ್ತೀಚೆಗೆ ಸೇರಿಸಲಾಗಿದೆ',
    new: 'ಹೊಸ',
    sold: 'ಮಾರಾಟ',
    viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    quickContact: 'ತ್ವರಿತ ಸಂಪರ್ಕ',
    quickContactSubtitle: 'ಯಾವುದೇ ವಿಚಾರಣೆಗಾಗಿ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    name: 'ಹೆಸರು',
    phone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    email: 'ಇಮೇಲ್',
    message: 'ಸಂದೇಶ',
    submit: 'ಸಲ್ಲಿಸಿ',
    submitEnquiry: 'ವಿಚಾರಣೆಯನ್ನು ಸಲ್ಲಿಸಿ',
    enquirySuccess: 'ಧನ್ಯವಾದಗಳು! ನಾವು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.',
    thanksForSubmission: 'ನಿಮ್ಮ ಸಲ್ಲಿಕೆಗೆ ಧನ್ಯವಾದಗಳು',
    ctaTitle: 'ನಿಮ್ಮ ಪರಿಪೂರ್ಣ ಕಾರನ್ನು ಹುಡುಕಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
    ctaSubtitle: 'ನಮ್ಮ ಶೋರೂಮ್ಗೆ ಭೇಟಿಯನ್ನು ಬುಕ್ ಮಾಡಿ ಅಥವಾ ಇಂದು ನಮ್ಮ ತಜ್ಞರೊಂದಿಗೆ ಮಾತನಾಡಿ',
    talkToExpert: 'ತಜ್ಞರೊಂದಿಗೆ ಮಾತನಾಡಿ',
    exploreCars: 'ಕಾರುಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    showroomAddress: 'ಶೋರೂಮ್ ವಿಳಾಸ',
    workingHours: 'ಕೆಲಸದ ಸಮಯಗಳು',
    mondayFriday: 'ಸೋಮವಾರ - ಶುಕ್ರವಾರ',
    saturday: 'ಶನಿವಾರ',
    sunday: 'ಭಾನುವಾರ',
    closed: 'ಮುಚ್ಚಲಾಗಿದೆ',
    followUs: 'ನಮ್ಮನ್ನು ಅನುಸರಿಸಿ',
    allRightsReserved: 'ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ',
    firstName: 'ಮೊದಲ ಹೆಸರು',
    lastName: 'ಕೊನೆಯ ಹೆಸರು',
    location: 'ಸ್ಥಳ',
    locationPlaceholder: 'ನಗರ, ರಾಜ್ಯ ಅಥವಾ ಪ್ರದೇಶ',
    save: 'ಉಳಿಸಿ',
    saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    profileUpdated: 'ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ.',
    profileUpdateFailed: 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲು ವಿಫಲವಾಯಿತು.',
    editProfileSubtitle: 'ನಿಮ್ಮ ಖಾತೆ ಮಾಹಿತಿಯನ್ನು ವೀಕ್ಷಿಸಿ ಮತ್ತು ಸಂಪಾದಿಸಿ',
    emailNotEditable: 'ಇಮೇಲ್ ಅನ್ನು ಬದಲಾಯಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
  },
  te: {
    home: 'హోమ్',
    cars: 'కార్లు',
    compare: 'సరిపోల్చండి',
    customerEnquiry: 'కస్టమర్ విచారణ',
    about: 'గురించి',
    contact: 'సంప్రదింపు',
    login: 'లాగిన్',
    signUp: 'సైన్ అప్',
    continueWithGoogle: 'Google తో కొనసాగించండి',
    forgotPassword: 'పాస్వర్డ్ మర్చిపోయారా?',
    wishlist: 'ఇష్టపడిన జాబితా',
    logout: 'లాగ్అవుట్',
    moreInformation: 'మరిన్ని సమాచారం',
    yourProfile: 'మీ ప్రొఫైల్',
    adminPanel: 'అడ్మిన్ ప్యానెల్',
    adminLogin: 'అడ్మిన్ లాగిన్',
    notifications: 'నోటిఫికేషన్‌లు',
    selectLanguage: 'భాషను ఎంచుకోండి',
    fullName: 'పూర్తి పేరు',
    confirmPassword: 'పాస్వర్డ్ నిర్ధారించండి',
    passwordStrength: 'పాస్వర్డ్ బలం',
    weak: 'బలహీనమైన',
    medium: 'మధ్యస్థం',
    strong: 'బలమైన',
    signupSuccess: 'ఖాతా విజయవంతంగా సృష్టించబడింది! దయచేసి లాగిన్ చేయండి.',
    invalidCredentials: 'చెల్లని ఇమెయిల్ లేదా పాస్వర్డ్.',
    emailRegistered: 'ఇమెయిల్ ఇప్పటికే నమోదు చేయబడింది.',
    passwordMismatch: 'పాస్వర్డ్లు సరిపోలడం లేదు.',
    enterEmail: 'మీ ఇమెయిల్ నమోదు చేయండి',
    enterPassword: 'మీ పాస్వర్డ్ నమోదు చేయండి',
    resetPassword: 'పాస్వర్డ్ రీసెట్ చేయండి',
    sendResetLink: 'రీసెట్ లింక్ పంపండి',
    backToLogin: 'లాగిన్‌కు తిరిగి వెళ్ళు',
    passwordResetSent: 'పాస్వర్డ్ రీసెట్ లింక్ మీ ఇమెయిల్‌కు పంపబడింది.',
    loginAsAdmin: 'అడ్మిన్‌గా లాగిన్ అవ్వండి',
    loginAsUser: 'యూజర్‌గా లాగిన్ అవ్వండి',
    // Home Page
    heroTitle: 'నమ్మకమైన రెండవ చేతి కారు మార్కెట్',
    heroSubtitle: 'పారదర్శక ధర మరియు నాణ్యత హామీతో మీ పరిపూర్ణ వాడుక కారును కనుగొనండి',
    viewCars: 'కార్లను వీక్షించండి',
    bookVisit: 'సందర్శనను బుక్ చేయండి',
    aboutTitle: 'ఎందుకు మమ్మల్ని ఎంచుకోవాలి?',
    aboutDescription: 'మేము రెండవ చేతి కారు మార్కెట్లో సంవత్సరాల అనుభవం కలిగిన నమ్మకమైన షోరూమ్. ప్రతి వాహనం నాణ్యత తనిఖీ చేయబడింది, మరియు మేము నమ్మకమైన విక్రేతలతో పారదర్శక ధర నిర్ణయాన్ని అందిస్తాము.',
    yearsExperience: 'సంవత్సరాల అనుభవం',
    qualityChecked: 'నాణ్యత తనిఖీ చేసిన వాహనాలు',
    transparentPricing: 'పారదర్శక ధర',
    trustedSellers: 'నమ్మకమైన విక్రేతలు',
    verifiedCars: 'ధృవీకరించబడిన కార్లు',
    trustedDealers: 'నమ్మకమైన డీలర్లు',
    customerSatisfaction: 'కస్టమర్ సంతృప్తి',
    recentlySold: 'ఇటీవల అమ్మబడింది',
    recentlyAdded: 'ఇటీవల జోడించబడింది',
    new: 'కొత్త',
    sold: 'అమ్మబడింది',
    viewDetails: 'వివరాలను వీక్షించండి',
    quickContact: 'త్వరిత సంప్రదింపు',
    quickContactSubtitle: 'ఏదైనా విచారణలకు మమ్మల్ని సంప్రదించండి',
    name: 'పేరు',
    phone: 'ఫోన్ నంబర్',
    email: 'ఇమెయిల్',
    message: 'సందేశం',
    submit: 'సమర్పించండి',
    submitEnquiry: 'విచారణను సమర్పించండి',
    enquirySuccess: 'ధన్యవాదాలు! మేము త్వరలో మిమ్మల్ని సంప్రదిస్తాము.',
    thanksForSubmission: 'మీ సమర్పణకు ధన్యవాదాలు',
    ctaTitle: 'మీ పరిపూర్ణ కారును కనుగొనడానికి సిద్ధంగా ఉన్నారా?',
    ctaSubtitle: 'మా షోరూమ్కు సందర్శనను బుక్ చేయండి లేదా ఈ రోజు మా నిపుణులతో మాట్లాడండి',
    talkToExpert: 'నిపుణులతో మాట్లాడండి',
    exploreCars: 'కార్లను అన్వేషించండి',
    showroomAddress: 'షోరూమ్ చిరునామా',
    workingHours: 'పని గంటలు',
    mondayFriday: 'సోమవారం - శుక్రవారం',
    saturday: 'శనివారం',
    sunday: 'ఆదివారం',
    closed: 'మూసివేయబడింది',
    followUs: 'మమ్మల్ని అనుసరించండి',
    allRightsReserved: 'అన్ని హక్కులు రక్షించబడ్డాయి',
    firstName: 'మొదటి పేరు',
    lastName: 'చివరి పేరు',
    location: 'స్థానం',
    locationPlaceholder: 'నగరం, రాష్ట్రం లేదా ప్రాంతం',
    save: 'సేవ్ చేయండి',
    saving: 'సేవ్ చేస్తోంది...',
    profileUpdated: 'ప్రొఫైల్ విజయవంతంగా అప్డేట్ చేయబడింది.',
    profileUpdateFailed: 'ప్రొఫైల్ అప్డేట్ చేయడం విఫలమైంది.',
    editProfileSubtitle: 'మీ ఖాతా సమాచారాన్ని వీక్షించండి మరియు సవరించండి',
    emailNotEditable: 'ఇమెయిల్ మార్చలేరు',
    loading: 'లోడ్ అవుతోంది...',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('preferredLanguage', lang);
  };

  // Load saved language preference on mount
  React.useEffect(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage');
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

